const linguas = (prefix) => {
return `✪╔◦◦━━┉┄►ஜ۩۞۩ஜ◄┄┉━━◦╗✪\n
	                   BOT UnitedKingdom\n\n ✪╚◦◦━━┉┄►ஜ۩۞۩ஜ◄┄┉━━◦╝✪\n\n
                     *_COMANDOS DE FALA_*\n\n
\`\`\`para usar esse comando digite ${prefix}fala o codigo da lingua e o texto com no maximo 300 caracteres!!!\`\`\`\n\n
af = *Afrikaans;*
sq = *Albanian;*
ar = *Arabic;*
hy = *Armenian;*
ca = *Catalan;*
zh = *Chinese;*
zh-cn = *Chinese(Mandarin/China);*
zh-tw = *Chinese(Mandarin/Taiwan);*
zh-yue = *Chinese(Cantonese);*
hr = *Croatian;*
cs = *Czech;*
da = *Danish;*
nl = *Dutch;*
en = *English;*
en-au = *English(Australia);*
en-uk = *English(UnitedKingdom);*
en-us = *English(UnitedStates);*
eo = *Esperanto;*
fi = *Finnish;*
fr = *French;*
de = *German;*
el = *Greek;*
ht = *HaitianCreole;*
hi = *Hindi;*
hu = *Hungarian;*
is = *Icelandic;*
id = *Indonesian;*
it = *Italian;*
ja = *Japanese;*
ko = *Korean;*
la = *Latin;*
lv = *Latvian;*
mk = *Macedonian;*
no = *Norwegian;*
pl = *Polish;*
pt = *Portuguese;*
pt-br = *Portuguese(Brazil);*
ro = *Romanian;*
ru = *Russian;*
sr = *Serbian;*
sk = *Slovak;*
es = *Spanish;*
es-es = *Spanish(Spain);*
es-us = *Spanish(UnitedStates);*
sw = *Swahili;*
sv = *Swedish;*
ta = *Tamil;*
th = *Thai;*
tr = *Turkish;*
vi = *Vietnamese;*
cy = *Welsh.*
`
}
exports.linguas = linguas